version: 2.1

orbs:
  node: circleci/node@4.1

jobs:
  install_dependencies:
    docker:
      - image: node:18
    steps:
      - checkout
      - restore_cache:
          key: dependency-cache-{{ checksum "package.json" }}
      - run: npm install
      - run: npm run frontend:install
      - run: npm run backend:install
      - save_cache:
          key: dependency-cache-{{ checksum "package.json" }}
          paths:
            - ./node_modules
            - ./store/store-frontend/node_modules
            - ./store/store-backend/node_modules

  build_frontend:
    docker:
      - image: node:18
    steps:
      - checkout
      - restore_cache:
          key: dependency-cache-{{ checksum "package.json" }}
      - run: npm run frontend:build

  build_backend:
    docker:
      - image: node:18
    steps:
      - checkout
      - restore_cache:
          key: dependency-cache-{{ checksum "package.json" }}
      - run: npm run backend:build

  # Füge dies hinzu, wenn du Backend-Tests hast
  test_backend:
    docker:
      - image: node:18
    steps:
      - checkout
      - restore_cache:
          key: dependency-cache-{{ checksum "package.json" }}
      - run: npm run backend:test

workflows:
  version: 2
  build_and_test:
    jobs:
      - install_dependencies
      - build_frontend:
          requires:
            - install_dependencies
      - build_backend:
          requires:
            - install_dependencies
      # Füge dies hinzu, wenn du Backend-Tests hast
      - test_backend:
          requires:
            - build_backend
