version: 2.1

orbs:
  node: circleci/node@4.1
  aws-cli: circleci/aws-cli@1.3.0
jobs:
  install_dependencies:
    docker:
      - image: "cimg/base:stable"
    steps:
      - checkout
      - restore_cache:
          key: dependency-cache-{{ checksum "package.json" }}
      - run: npm install
      - run: npm run frontend:install
      - run: npm run backend:install
      - save_cache:
          key: dependency-cache-{{ checksum "package.json" }}
          paths:
            - ./node_modules
            - ./store/store-frontend/node_modules
            - ./store/store-backend/node_modules

  lint_backend:
    docker:
      - image: node:18
    steps:
      - checkout
      - restore_cache:
          key: dependency-cache-backend-{{ checksum "store/store-backend/package.json" }}
      - run:
          name: Lint Backend
          command: cd store/store-backend && npm run lint

  format_backend:
    docker:
      - image: node:18
    steps:
      - checkout
      - restore_cache:
          key: dependency-cache-backend-{{ checksum "store/store-backend/package.json" }}
      - run:
          name: Format Backend
          command: cd store/store-backend && npm run prettier

  lint_frontend:
    docker:
      - image: node:18
    steps:
      - checkout
      - restore_cache:
          key: dependency-cache-frontend-{{ checksum "store/store-frontend/package.json" }}
      - run:
          name: Lint Frontend
          command: cd store/store-frontend && npm run lint

  format_frontend:
    docker:
      - image: node:18
    steps:
      - checkout
      - restore_cache:
          key: dependency-cache-frontend-{{ checksum "store/store-frontend/package.json" }}
      - run:
          name: Format Frontend
          command: cd store/store-frontend && npm run prettier

  build_frontend:
    docker:
      - image: node:18
    steps:
      - checkout
      - restore_cache:
          key: dependency-cache-frontend-{{ checksum "store/store-frontend/package.json" }}
      - run:
          name: Build Frontend
          command: cd store/store-frontend && npm run build
      - run:
          name: Diagnose
          command: |
            ls -la store/store-frontend/dist
      - persist_to_workspace:
          root: .
          paths:
            - store/store-frontend/dist

  build_backend:
    docker:
      - image: node:18
    steps:
      - checkout
      - restore_cache:
          key: dependency-cache-backend-{{ checksum "store/store-backend/package.json" }}
      - run:
          name: Build Backend
          command: cd store/store-backend && npm run build
      - run:
          name: Diagnose
          command: |
            ls -la store/store-backend/dist
            ls -la store/store-backend/dist/src
      - persist_to_workspace:
          root: .
          paths:
            - store/store-backend/dist

  test_backend:
    docker:
      - image: node:18
      - image: postgres:13
        environment:
          POSTGRES_HOST: 127.0.0.1
          POSTGRES_DB: dbtest
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: asds
    environment:
      DOCKERIZE_VERSION: v0.6.1
    steps:
      - checkout
      - restore_cache:
          key: dependency-cache-backend-{{ checksum "store/store-backend/package.json" }}
      - run:
          name: Install Dockerize
          command: |
            wget https://github.com/jwilder/dockerize/releases/download/$DOCKERIZE_VERSION/dockerize-linux-amd64-$DOCKERIZE_VERSION.tar.gz
            tar -C /usr/local/bin -xzvf dockerize-linux-amd64-$DOCKERIZE_VERSION.tar.gz
            rm dockerize-linux-amd64-$DOCKERIZE_VERSION.tar.gz
      - run:
          name: Warten auf die Datenbank
          command: dockerize -wait tcp://localhost:5432 -timeout 1m
      - run:
          name: Backend-Tests
          command: cd store/store-backend && npm run test
          environment:
            DATABASE_URL: postgres://postgres:asds@localhost:5432/dbtest

  deploy_frontend:
    docker:
      - image: node:18
    environment:
      AWS_DEFAULT_REGION: us-east-1
    steps:
      - checkout
      - attach_workspace:
          at: .
      - restore_cache:
          key: dependency-cache-frontend-{{ checksum "store/store-frontend/package.json" }}
      - run:
          name: Install AWS CLI
          command: |
            curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o "awscliv2.zip"
            unzip awscliv2.zip
            ./aws/install
      - run:
          name: Deploy to S3
          command: |
            ls -la store/store-frontend/dist
            aws s3 sync store/store-frontend/dist s3://udacity-bucket-00001

  deploy_backend:
    docker:
      - image: node:18
    environment:
      AWS_DEFAULT_REGION: us-east-1
    steps:
      - checkout
      - aws-cli/setup
      - attach_workspace:
          at: .
      - restore_cache:
          key: dependency-cache-backend-{{ checksum "store/store-backend/package.json" }}
      - run:
          name: Diagnose
          command: |
            ls -la store/store-backend/dist
            ls -la store/store-backend/dist/src

      - run:
          name: Deploy to Elastic Beanstalk
          command: |
           cd store/store-backend
           eb deploy Testumgebung-env


workflows:
  version: 2
  build_and_test:
    jobs:
      - install_dependencies
      - lint_backend:
          requires:
            - install_dependencies
      - format_backend:
          requires:
            - install_dependencies
      - lint_frontend:
          requires:
            - install_dependencies
      - format_frontend:
          requires:
            - install_dependencies
      - build_frontend:
          requires:
            - install_dependencies
      - build_backend:
          requires:
            - install_dependencies
      - test_backend:
          requires:
            - build_backend
      - deploy_frontend:
          requires:
            - build_frontend
      - deploy_backend:
          requires:
            - build_backend
