version: 2.1
orbs:
  node: circleci/node@4.1.0
  aws-cli: circleci/aws-cli@1.3.1
jobs:
  build:
    docker:
      - image: "cimg/base:stable"
    steps:
      - node/install
      - checkout
      - aws-cli/setup
      - run:
          name: Front-End Install
          command: |
            npm run frontend:install
      - run:
          name: Front-End Lint
          command: |
            npm run frontend:lint
      - run:
          name: Front-End Prettier
          command: |
            cd store/store-frontend && npm run prettier            
      - run:
          name: Front-End Test
          command: |
            npm run frontend:test
      - run:
          name: Front-End Build
          command: |
            npm run frontend:build
      - run:
          name: Back-End Install
          command: |
            npm run backend:install
      - run:
          name: Back-End Lint
          command: |
            npm run backend:lint
      - run:
          name: Back-End Prettier
          command: |
            cd store/store-backend && npm run prettier
      - run:
          name: Back-End Build
          command: |
            npm run backend:build
      - run:
          name: Deploy App
          command: |
            npm run frontend:deploy
