version: 2.1
orbs:
  node: circleci/node@4.1.0
  aws-cli: circleci/aws-cli@1.3.1
jobs:
  lint_prettier_build-deploy:
    docker:
      - image: "cimg/base:stable"
    steps:
      - node/install
      - checkout
      - aws-cli/setup
      - run:
          name: Install Elastic Beanstalk CLI
          command: |
            sudo apt-get update
            sudo apt-get install -y python3-pip
            curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o "awscliv2.zip"
            unzip awscliv2.zip
            sudo ./aws/install --bin-dir /usr/local/bin --install-dir /usr/local/aws-cli --update
            pip3 install awsebcli --upgrade --user
      - run:
          name: Front-End Install
          command: |
            npm run frontend:install
      - run:
          name: Front-End Lint
          command: |
            npm run frontend:lint
      - run:
          name: Front-End Prettier
          command: |
            cd store/store-frontend && npm run prettier
      - run:
          name: Front-End Build
          command: |
            npm run frontend:build
      - run:
          name: Back-End Install
          command: |
            npm run backend:install
      - run:
          name: Back-End Lint
          command: |
            npm run backend:lint
      - run:
          name: Back-End Prettier
          command: |
            cd store/store-backend && npm run prettier
      - run:
          name: Back-End Build
          command: |
            npm run backend:build
      - run :
          name: Copy package
          command: |
            cp store/store-backend/src/package.json store/store-backend/dist/src/package.json
      - run:
          name: Deploy Front-End
          command: |
            cd store/store-frontend &&
            chmod +x bin/deploy.sh && bin/deploy.sh
      - run:
           name: Deploy Back-End
           command: |
            cd store/store-backend &&
            chmod +x bin/deploy.sh && bin/deploy.sh

  
workflows:
  version: 2
  lint_prettier_build-deploy:
    jobs:
      - lint_prettier_build-deploy:
          filters:
            branches:
              only:
                - main